#ifndef JOS_INC_TRAP_H
#define JOS_INC_TRAP_H

// Trap numbers
// These are processor defined:
#define T_DIVIDE     0		// 除法错误 divide error
#define T_DEBUG      1		// 调试异常 debug exception
#define T_NMI        2		// 不可屏蔽中断 non-maskable interrupt
#define T_BRKPT      3		// 断点 breakpoint
#define T_OFLOW      4		// 溢出 overflow
#define T_BOUND      5		// 边界检查 bounds check
#define T_ILLOP      6		// 非法操作码 illegal opcode
#define T_DEVICE     7		// 设备不可用 evice not available
#define T_DBLFLT     8		// 双重错误 double fault
/* #define T_COPROC  9 */	// reserved (not generated by recent processors)
#define T_TSS       10		// 无效的任务切换段 invalid task switch segment
#define T_SEGNP     11		// 段不存在 egment not present
#define T_STACK     12		// 栈异常 stack exception
#define T_GPFLT     13		// 通用保护错误 general protection fault
#define T_PGFLT     14		// 页面错误 page fault
/* #define T_RES    15 */	// reserved
#define T_FPERR     16		// 浮点错误 floating point error
#define T_ALIGN     17		// 对齐检查 aligment check
#define T_MCHK      18		// 机器检查 machine check
#define T_SIMDERR   19		// SIMD浮点错误 SIMD floating point error

// These are arbitrarily chosen, but with care not to overlap
// processor defined exceptions or interrupt vectors.
// 一共有256个中断号，这里的中断号48，是任意取的一个较高位置中断，低位置中断已经被系统使用了
#define T_SYSCALL   48		// system call
#define T_DEFAULT   500		// catchall 默认中断


// 硬件中断号从 IRQ_OFFSET开始
#define IRQ_OFFSET	32	// IRQ 0 corresponds to int IRQ_OFFSET

// Hardware IRQ numbers. We receive these as (IRQ_OFFSET+IRQ_WHATEVER)
#define IRQ_TIMER        0	// 定时器中断 对应的中断号为 32 + 0 = 32
#define IRQ_KBD          1	// 键盘中断 对应的中断号为 32 + 1 = 33
#define IRQ_SERIAL       4	// 键盘中断 对应的中断号为 32 + 4 = 36
#define IRQ_SPURIOUS     7	// 伪中断 对应的中断号为 32 + 7 = 39
#define IRQ_IDE         14	// IDE中断 对应的中断号为 32 + 14 = 46
#define IRQ_ERROR       19	// 错误中断 对应的中断号为 32 + 19 = 51

#ifndef __ASSEMBLER__

#include <inc/types.h>

// 存储使用 pusha （push all）汇编语言，压栈的通用寄存器顺序
struct PushRegs {
	/* registers as pushed by pusha */
	uint32_t reg_edi;
	uint32_t reg_esi;
	uint32_t reg_ebp;
	uint32_t reg_oesp;		/* Useless */
	uint32_t reg_ebx;
	uint32_t reg_edx;
	uint32_t reg_ecx;
	uint32_t reg_eax;
} __attribute__((packed));


// 这里的结构体，与 kern/trapentry.S 的 _alltraps 函数压栈的顺序 “反向” 对应（因为压栈是往下压，通常取值是往上取）。
// 使用这个结构体，可以很清晰的取出想要的寄存器值
struct Trapframe {
    struct PushRegs tf_regs;  // 保存通用寄存器的状态		
    uint16_t tf_es;           // 段寄存器 ES
    uint16_t tf_padding1;     // 填充使对齐
    uint16_t tf_ds;           // 段寄存器 DS
    uint16_t tf_padding2;     // 填充使对齐
    uint32_t tf_trapno;       // 中断或异常号
    /* 以下由 x86 硬件定义 */
    uint32_t tf_err;          // 错误码（如果有的话）
    uintptr_t tf_eip;         // 指令指针 EIP
    uint16_t tf_cs;           // 代码段寄存器 CS
    uint16_t tf_padding3;     // 填充使对齐
    uint32_t tf_eflags;       // 标志寄存器 EFLAGS
    /* 以下仅在跨权限级别时，如从用户态到内核态 */
    uintptr_t tf_esp;         // 堆栈指针 ESP
    uint16_t tf_ss;           // 堆栈段寄存器 SS
    uint16_t tf_padding4;     // 填充使对齐			
} __attribute__((packed));


// 在用户态陷入缺页处理时候使用，进行用户态异常处理，保存原本用户程序的状态
struct UTrapframe {
	/* information about the fault */
	uint32_t utf_fault_va;	// 保存了触发缺页中断的虚拟地址/* va for T_PGFLT, 0 otherwise */
	uint32_t utf_err;		// 保存了错误代码，描述了中断或异常的原因
	/* trap-time return state */
	struct PushRegs utf_regs;	// 这个字段保存了当时的通用寄存器的值。
	uintptr_t utf_eip;			// 保存了触发异常的指令地址（即异常发生时处理器的 EIP 寄存器的值），这有助于在处理完异常后能够返回并继续执行异常发生前的指令。
	uint32_t utf_eflags;		// 保存了当时的 EFLAGS 寄存器的值，这包含了许多标志位，用于控制处理器状态和反映处理器的当前状态。
	/* the trap-time stack to return to */
	uintptr_t utf_esp;			// 保存了当时的堆栈指针（ESP 寄存器）的值，即当异常发生时，程序所使用的堆栈的位置。
} __attribute__((packed));		// 表示这个结构体在内存中按顺序紧密排列，没有任何填充字节。这在处理低级硬件操作时很常见，以确保数据在内存中的精确布局。

#endif /* !__ASSEMBLER__ */

#endif /* !JOS_INC_TRAP_H */
